name: "Setup Node.js development environment"
description: "Setup Node.js development environment for GitHub Actions"

runs:
  using: composite
  steps:
    - name: Setup | pnpm
      uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4.4.0

    - name: Setup | Node.js
      uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
      with:
        node-version-file: .tool-versions
        cache: pnpm

    - name: Setup | Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
