minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - "@shun-shobon/style-guide"

onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - esbuild
  - sharp
  - unrs-resolver
  - workerd

publicHoistPattern:
  - "*eslint*"

saveExact: true

strictDepBuilds: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - "chokidar@4.0.3"
  - "vite@6.4.1"
  - "semver@6.3.1"
  - "ts-api-utils@2.3.0"
