[[timeline]]
id = "2003-04-22"
title = "誕生"
startedAt = "2003-04-22"

[[timeline]]
id = "2020-04-01"
title = "長野工業高等専門学校 電子情報工学科"
startedAt = "2020-04-01"
endedAt = "2023-03-31"
description = """
研究室ではホログラフィに関する研究を行い、3Dモデルをホログラムに変換する手法の研究開発に取り組んでいました。
また、部活では情報技術研究部に所属し、高専プロコンなどのコンテストでの入賞を目指して活動していました。
"""

[[timeline]]
id = "2020-08-01"
title = "Open Hack U 2020 Online Vol.1に参加"
startedAt = "2020-08-01"

[[timeline]]
id = "2020-10-01"
title = "C-Style株式会社"
startedAt = "2020-10-01"
endedAt = "2024-06-30"

[[timeline]]
id = "2021-01-01"
title = "サポーターズウィンターハッカソンにて最優秀賞を受賞"
startedAt = "2021-01-01"

[[timeline]]
id = "2021-03-01"
title = "Open Hack U 2020 Online Vol.5に参加"
startedAt = "2021-03-01"

[[timeline]]
id = "2021-10-01"
title = "全国高専プログラミングコンテスト2021にて課題部門特別賞を受賞"
startedAt = "2021-10-01"

[[timeline]]
id = "2022-03-01"
title = "ピクシブ株式会社"
startedAt = "2022-03-01"

[[timeline]]
id = "2022-05-01"
title = "基本情報技術者試験に合格"
startedAt = "2022-05-01"

[[timeline]]
id = "2022-09-01"
title = "Chatwork株式会社"
startedAt = "2022-09-01"

[[timeline]]
id = "2023-11-01"
title = "ピクシブ株式会社"
startedAt = "2023-11-01"
endedAt = "2024-11-01"

[[timeline]]
id = "2023-12-01"
title = "応用情報技術者試験に合格"
startedAt = "2023-12-01"

[[timeline]]
id = "2024-03-01"
title = "Web Speed Hackathon 2024に参加"
startedAt = "2024-03-01"

[[timeline]]
id = "2024-04-01"
title = "東京農工大学 工学部 知能情報システム工学科"
startedAt = "2024-04-01"
endedAt = "present"

[[timeline]]
id = "2024-07-01"
title = "ネットワークスペシャリスト試験に合格"
startedAt = "2024-07-01"

[[timeline]]
id = "2024-08-01"
title = "Open Hack U 2024 TOKYO Vol.2に参加"
startedAt = "2024-08-01"

[[timeline]]
id = "2024-09-01"
title = "Web Developers Conference 2024にて登壇"
startedAt = "2024-09-01"

[[timeline]]
id = "2024-11-01"
title = "技育展 2024 決勝進出"
startedAt = "2024-11-01"

[[timeline]]
id = "2024-12-01"
title = "株式会社CAM"
startedAt = "2024-12-01"
endedAt = "2025-02-28"

[[timeline]]
id = "2024-12-10"
title = "ISUCON14に参加"
startedAt = "2024-12-10"

[[timeline]]
id = "2024-12-30"
title = "C105に出展"
startedAt = "2024-12-30"

[[timeline]]
id = "2025-02-01"
title = "技育博でDeNA賞を受賞"
startedAt = "2025-02-01"

[[timeline]]
id = "2025-03-01"
title = "株式会社AbemaTV"
startedAt = "2025-03-01"
endedAt = "2025-05-31"

[[timeline]]
id = "2025-03-20"
title = "Web Speed Hackathon 2025にて優勝"
startedAt = "2025-03-01"


[[timeline]]
id = "2025-06-01"
title = "株式会社CyberLCH"
startedAt = "2025-06-01"
endedAt = "present"
